- hosts: localhost                  
  tasks:                                                     
    - uri:                                                               
        url: https://api.github.com/repos/istio/istio/releases/latest
        return_content: true    
      register: istio_latest

    - uri:
        url: https://api.github.com/repos/openshift/origin/releases/latest
        return_content: true
      register: oc_latest
    

   
    - name: "Download Istio"
      become: yes
      unarchive:
       src: "{{ istio_latest | json_query('json.assets[0].browser_download_url') }}"
       dest: .
       remote_src: yes

    - name: "Download oc"
      become: yes
      unarchive:
        src: "{{ oc_latest | json_query('json.assets[1].browser_download_url') }}"
        dest: . 
        remote_src: yes

