#!/bin/bash

echo -e "Running Cluster up...\n"
(
cd
oc config current-context 
oc cluster up --skip-registry-check
sleep 2.5
oc config current-context 
oc login --insecure-skip-tls-verify -u system:admin
oc adm policy add-role-to-user admin admin
)
