#!/bin/bash

minishift_version="v3.11.0"
cpus="2"
mem="8"
vm_driver="virtualbox"
profile="test"

if  command -v minishift >/dev/null 2>&1; then
  if command -v oc >/dev/null 2>&1; then

    if [ "$1" = "-f" ]; then
       echo "force deleting stuff"
       minishift images delete $(minishift images list)
       minishift delete -f  --clear-cache
    fi

    minishift profile set $profile
    minishift config set memory $memGB
    minishift config set cpus $cpus
    minishift config set vm-driver $vm_driver
    minishift config set image-caching true
    minishift addon enable admin-user
    minishift config set openshift-version $minishift_version
    minishift addon enable anyuid

    minishift start
    minishift ssh -- sudo setenforce 0 

    sleep 5
    echo "loging into minishift"

    oc login $(minishift ip):8443 -u admin -p admin
    minishift console
  else 
    echo -e "Can not run oc ...\n"
    exit 1;
  fi 
else
    echo -e "Can not run minishift ...\n"
    exit 1;
fi