#!/bin/bash
set -e

# See: https://redhat-developer-demos.github.io/istio-tutorial/istio-tutorial/1.0.0/index.html
# Need to have a started minishift cluster 
# Need to have cloned the istio repo 
# Need to have added istioctl and oc in to $PATH

if [ ! -d "$1" ]; then
  echo "Istio repo does not exist"
  exit 1;
elif [ ! -f "$1/install/kubernetes/istio-demo.yaml" ]; then 
    echo "$1 does not contain the file /install/kubernetes/istio-demo.yaml"
    exit 1;
fi

for b in oc istioctl minishift; do
  if ! command -v $b >/dev/null 2>&1; then
    echo "$b not in path"
    exit 1;
  fi
done 


if [[ $(minishift status | head -1 | awk '{print $2}') != 'Running' ]]; then
  echo "Minishift is not Running"
  exit 1;
fi

# need to be login as admin 

echo -e "Installing Istio on Minishft ... "

oc apply -f "$1/install/kubernetes/helm/istio/templates/crds.yaml"
oc apply -f "$1/install/kubernetes/istio-demo.yaml"
oc project istio-system

oc expose svc istio-ingressgateway
oc expose svc servicegraph
oc expose svc grafana
oc expose svc prometheus
oc expose svc tracing