#!/usr/bin/bash

echo "Updating dotfiles"
df_dir="$HOME/dotfiles"

if [ ! -d $df_dir ]; then
    echo "$df_dir dir does not exist"
    exit 1;
fi 

cd $df_dir
git remote update && git checkout master && git pull
find . -type f -regex ".*bashrc\|.*gitconfig\|.*gitignore_global\|.*vimrc" -exec cp {} $HOME \;